[project]
name = "dictos"
revision = "1.0"

[profiles.default]
TURSO_ORG_SLUG = { description = "The slug of your Turso organization", required = true }
TURSO_PLATFORM_TOKEN = { description = "API token to for Turso platform operations", required = true }
JWT_SECRET= { description = "Secret for signing JSON Web Tokens", required = true }

[profiles.development]
JWT_SECRET= { description = "Secret for signing JSON Web Tokens", generate = true, type = "base64" }
